version: "3.8"

services:
  backend:
    build: ./backend
    container_name: dj-backend

    restart: always
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456789
    depends_on:
      - mysql
    networks:
      - djnet

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: http://localhost:8080

    container_name: dj-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - djnet

  mysql:
    image: mysql:8.0
    container_name: dj-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=dj_booking
      - MYSQL_ROOT_PASSWORD=123456789
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysql -uroot -p123456789 -e 'SELECT 1'" ]
      interval: 10s
      timeout: 5s
      retries: 5


    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - djnet

volumes:
  mysql-data:

networks:
  djnet:
